<center> <h1> Programming for Data Analytics 2021 NumPy Assignment </h1> </center>


<div align="center"> <b> Student Name: Kate McGrath </b> </div>
<div align="center"> <b> Student Number: G00398908 </b>  </div>
<div align="center"> <b> Submission Date: 11/11/2021 </b> </div>

<center> <h1> Part One: Overview of NumPy Package </h1> </center>

### Introduction

NumPy, or Numerical Python, is one of the most widely used scientific libraries in Python programming [1]. 

An open-source library, created in 2005 by Travis Oliphant [2], it has become the de facto standard for working with numerical data in Python, and is used by everyone from beginners to experienced researchers at the cutting edge of scientific and commercial R&D [3]. Additionally, several other Python analytical libraries have been built on top of NumPy, including Pandas, Scikit-learn and Matplotlib [1]. 

This notebook provides a comprehensive overview of the NumPy package, its key features and instructions for their use.

### Getting Started with NumPy
The only prerequisite to installing NumPy is Python itself. For convenience, the Anaconda distribution is recommended for beginners as it comes with NumPy, Python and other statistical Python packages pre-installed. 

To install NumPy on its own, the following command can be used:


In [ ]:
pip install numpy

In order to use NumPy, the library should be imported using the following command:

In [ ]:
import numpy as np

### Overview of Numpy Arrays ##


NumPy's core object is the multidimensional array (ndarray), which is essentially a fast and flexible container, built to facilitate batch numerical operations on blocks of data. Ndarrys are homogeneous, meaning that all data stored within the array must be of the same type. Each array has a shape, which is a tuple that indicates the nu

An ndarray can be considered as a grid of values, where the elements are analogous to the **rows**, while the indexes correspond to the **columns** [4][7]. An array with a single column (one-dimensional) is referred to as a vector, and matrices are arrays with multiple columns **(n-dimensional)**.


<div align="center"> <b>Figure One: 1, 2 and 3-D NumPy Arrays</b> </div>



![One, two and Three Dimensional Numpy Arrays](https://miro.medium.com/max/1400/1*zOyDfDLcCasA02D-S_ocCA.png)
[Source](https://towardsdatascience.com/numpy-basics-for-people-in-a-hurry-8e05781503f) 

Run the below code to see examples of one-dimensional, two-dimensional and three-dimensional arrays.

In [4]:
oneDArray = np.array ([1,2,3])
print(oneDArray)

twoDArray = np.array ([(1,2), (3,4)])
print(twoDArray)

threeDArray = np.array ([(1,2), (3,4), (5,6)])
print(threeDArray)

[1 2 3]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]


In NumPy, dimensions are also referred to as **axes**. They are numbered, starting at 0. In a two-dimensional array, the rows are indicated as "axis 0", while the columns are at "axis 1". The number of the axis increases in accordance with the number of dimensions; in 3-D arrays, an additional "axis 2" will be present [2].

## References
1. Analytics Vidhya. 2021. The Ultimate NumPy Tutorial for Data Science Beginners. [online] Available at: <https://www.analyticsvidhya.com/blog/2020/04/the-ultimate-numpy-tutorial-for-data-science-beginners/> [Accessed 16 October 2021].

2. W3schools.com. 2021. Introduction to NumPy. [online] Available at: <https://www.w3schools.com/python/numpy/numpy_intro.asp> [Accessed 16 October 2021].

3. Numpy.org. 2021. NumPy: the absolute basics for beginners — NumPy v1.21 Manual. [online] Available at: <https://numpy.org/doc/stable/user/absolute_beginners.html> [Accessed 16 October 2021].

4. Numpy.org. 2021. NumPy quickstart — NumPy v1.21 Manual. [online] Available at: <https://numpy.org/doc/stable/user/quickstart.html> [Accessed 16 October 2021].

5. Medium. 2021. NumPy for Dummies. [online] Available at: <https://medium.datadriveninvestor.com/numpy-for-dummies-3dbd5f946731> [Accessed 16 October 2021].

6. Numpy.org. 2021. Installing Numpy. [online] Available at: <https://numpy.org/install/> [Accessed 16 October 2021].

7. DataCamp. 2021. [online] Available at: <https://www.datacamp.com/community/tutorials/python-numpy-tutorial#a> [Accessed 16 October 2021].